apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-api-app-dep
spec:
  selector:
    matchLabels:
      app: skys-api-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-api-app-pod
      labels:
        app: skys-api-app
    spec:
      containers:
        - name: nestjs
          image: skys-api:nestjs
          imagePullPolicy: Never
          volumeMounts:
            - name: nestjs-app
              mountPath: /var/www
          ports:
            - containerPort: 3000
      volumes:
        - name: nestjs-app
          hostPath:
            path: /Users/hiroki/Project/skys/client-api/app
            type: DirectoryOrCreate