apiVersion: v1
kind: Service
metadata:
  name: skys-client-api-app-svc
spec:
  type: NodePort
  selector:
    app: skys-client-api-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000